[project]
name = "co-370"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=12.0.3",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.7",
]
